// Auto-generated by Hardhat deploy script.
// DO NOT EDIT BY HAND. Re-run: npx hardhat run scripts/deploy.js --network localhost

export const CONTRACT_ADDRESSES = {
  ALUAssetRegistry: "0x5fbdb2315678afecb367f032d93f642f64180aa3",
  ALULogoToken: "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0",
};

export const HARDHAT_CHAIN_ID = 31337;
export const HARDHAT_RPC_URL = "http://127.0.0.1:8545";
